### ISSUE TITLE
Build instructions -j parameter

### ISSUE THREAD

**Issue by nickaleks** [hyperledger/iroha-api#37]
https://hyperledger.github.io/iroha-api/#linux-or-macos 
```
# Build 
cmake -H. -Bbuild
cmake --build build -- -j4
```
It is better to leave number of processes as a variable, than hardcoded.

**Comment by neewy** [comment]
resolved

**Comment by neewy** [comment]
https://gist.github.com/neewy/39557aa444c3317aeffbdedd9f0f51e2/revisions
